# Generated by Kavia Code Generation Agent

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True, default="")),
                ("tags", models.CharField(blank=True, default="", max_length=255)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["is_archived"], name="api_note_is_arch_idx"),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["title"], name="api_note_title_idx"),
        ),
    ]
